### ISSUE TITLE
Debug BibLaTeX first name issue

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#11]
It seems that the BibLaTeX style has problems with generating labels in the Text when the bibligraphy database contains authors with many first names (Clark, Arthur B. C. etc.): The label in the text contains the initials such as "... some text (Clark, A. B. C. 2000) ..." instead of (Clark 2000).

Moreover, the algorithm generating the "et al." seems to be buggy: It works with three authors but not with more than 3.

**Comment by sieversMartin** [comment]
The first issue is probably caused by the feature "uniquename" to get unique citations names. It might be necessary to modify the BibTeX file.

The second one is not clear to me. The remark by Martin Leidig was about the change from maxcitenames=2 to 3

**Comment by sstrecker** [comment]
I'll ask Benjamin to review the bug report and let us know.

**Comment by sieversMartin** [comment]
The trick is to use not only `uniquename`, but also `uniquelist`. Please let me know, whether you still want to change this.

**Comment by sstrecker** [comment]
Ja:

http://tex.stackexchange.com/questions/84119/why-do-some-biblatex-options-need-to-be-set-in-the-preamble-and-cannot-be-called

Sent from a mobile device.

Am 14.02.2016 um 23:23 schrieb Martin Sievers <notifications@github.com<mailto:notifications@github.com>>:

The trick is to use not only uniquename, but also uniquelist. Please let me know, whether you still want to change this.

�

**Comment by sieversMartin** [comment]
Well, the problem was not an incorrect call of biblatex options, but a missing one ;-)

I'll change that.

**Comment by sieversMartin** [comment]
`uniquename=false` was added in commit 4c8ad5e9f1a817b2ed034572c9d9e53a42117c01

**Comment by sstrecker** [comment]
I changed to maxcitenames=2 after testing the latest commit.

Am 15.02.16, 22:43 schrieb "Martin Sievers" notifications@github.com:
