### ISSUE TITLE
Documentation: Add info for licenses

### ISSUE THREAD

**Issue by sieversMartin** [sstrecker/emisa-latex-package#12]
The emisa class now supports special licenses, namely CC-BY-NC-SA-3.0 and -4.0. The corresponding macros should be added to the documentation.

**Comment by sstrecker** [comment]
I should test this new feature. Can you let know how to use it properly?

**Comment by sieversMartin** [comment]
At the moment we have two macros: `\CCBYNCSAThree` and `\CCBYNCSAFour`. Just add one of these to the title section of the article, e.g.:

``` LaTeX
...
\authornote{This article extends an earlier conference paper, see ...}
\acknowledgements{}
\CCBYNCSAThree
```

Alternatively you can add an arbitrary license text by using `\license{This text is licensed under the LPPL1.3c}` or `\licence{This text is licensed under the LPPL1.3c}`.

All license information are added at the very end of the article.

**Comment by sstrecker** [comment]
Works! We should add this to the documentation for the editorial office.
