### ISSUE TITLE
Rename emisa.pdf to emisa-instructions.pdf

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#13]
The file emisa.pdf is easily overlooked. Could the file name be changed to emisa-instructions.pdf (or similar)?

**Comment by sieversMartin** [comment]
I have to check, whether this can be done directly. Otherwise we could add a symbolic link. In any case we have to check for CTAN's requirements.

**Comment by sstrecker** [comment]
If it is too much of a hassle, we leave it as emisa.pdf and point authors to the file on the journal's website.

**Comment by sieversMartin** [comment]
There will be three use cases:
1. Authors with a recent TeX distribution always get the latest version. With `texdoc emisa` they will get the corresponding documentation.
2. For authors who download the version from Github we could just add a symbolic link _emisa-instructions.pdf_ to the release linking to emisa.pdf
3. Authors who find emisa on CTAN usually know that the documentation is name \jobname.pdf. In addition this file is always marked as the documentation on the package's web site (on CTAN).

However, I will check, whether we add a _emisa-instructions.pdf_ to the CTAN release as well.

**Comment by sieversMartin** [comment]
I added a symlink emisa-instructions.pdf with commit 89bdb81f66434695935792d97cde0d488d19bae0
