### ISSUE TITLE
Change punctuation for \specialissuetitle

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#15]
Instead of
Vol. 11, No. 1 (31 Jan 2016). (Special Issue on Domain-Specific Modelling Languages)
we should opt for 
Vol. 11, No. 1 (31 Jan 2016). Special Issue on Domain-Specific Modelling Languages.

**Comment by sieversMartin** [comment]
Solved in 9585af107a1b7c758da97975a444c207f457b7bd
