### ISSUE TITLE
Add two macros \meta and \type

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#16]
\newcommand{\meta}[1]{{\texttt{\small #1}}}  % designate a meta type (meta class)
\newcommand{\type}[1]{\textsf{#1}}               % designate a type (class)

They should be used to refer to meta types and types, respectively. Whether the \small is needed, is up for discussion.

**Comment by sieversMartin** [comment]
Added in c43abe628d94b2e8c72cba78eff8d3281765c8f5
