### ISSUE TITLE
Feature request: Choosing between British English and American English

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#17]
In the future, we may accept papers in both UK (British) English and US (American) English which IMO affects the hyphenation patterns (babel package) and the set up of quotation marks (csquotes package).
It would be useful to be able to switch between the two by class options: british and american (or UKenglish and USenglish).

**Comment by sieversMartin** [comment]
I added corresponding options with commit 7e2aeae849dc236030a22040c757a9669f951e07 which modify `babel` and `csquotes` accordingly.

**Comment by sstrecker** [comment]
Thanks. I get an error when using the option 'british' or 'UKenglish', e.g., \documentclass[UKenglish]{emisa}.

babel Error: Unknown language 'american'. Either you have misspelled its name, ....

l.31 \select@language{american}

The class options 'american' and 'USenglish' both work.

**Comment by sieversMartin** [comment]
You have to compile twice if you change the main language of a LaTeX document, e.g. from `american` to `UKenglish`.

If the error remains, then please check, whether you have installed the american language correctly. This should be the case for almost all standard distributions.

**Comment by sstrecker** [comment]
Solution: Remove all temporary files from compilation before changing from british to american or vice versa. Then compile again.
