### ISSUE TITLE
emisa.pdf: Add USenglish and american as class option to the instructions

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#19]
The instructions currently only mention USenglish / british in the section on class option. The section on quotation marks already mentions USenglish / british.

**Comment by sieversMartin** [comment]
I was not sure, whether you want authors to know that options already. I will add the two new options to the documentation.

**Comment by sieversMartin** [comment]
Modified in be5d336b4931891c04e3d7a2db5ed4aca62b58a7
