### ISSUE TITLE
Add tracking to small caps with microtype package?

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#25]
Bringhurst (2008) on p. 30 recommends to add tracking to small caps. Von Dongen (2012) on p. 52 recommends to use

\usepackage[final,tracking=smallcaps,expansion=alltext,protrusion=true]{microtype}
\SetTracking{encoding=*,shape=sc}{50}

for a 5 percent tracking space for small caps.
Should we add this?

**Comment by sieversMartin** [comment]
I'll check with my personal typographic "gurus" tomorrow ;-)

**Comment by sieversMartin** [comment]
Done (cf. commit 10e8bdc)
