### ISSUE TITLE
emisa.cls: Feature request

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#3]
The class option ‘referee’ should suppress the output of the acknowledgements but not the output of \authornote.

**Comment by sieversMartin** [comment]
Would the \authornote in general not give too much information about the (anonymous) author, e.g. by naming a concrete corresponding article?

**Comment by sstrecker** [comment]
I agree but it is important for the reviewers to know whether the submission is based on an earlier publication. In order to anonymize the submission for double-blind review, the \authornote must not contain any identifying information but rather a sentence like "This paper is based on an earlier conference publication [reference omitted for review]".

**Comment by sstrecker** [comment]
After rethinking the issue, an alternative solution would be to have the class option 'review' (or 'referee') turn on a separate (initial) title page with full author information, abstract, keywords, acknowledgements and authornote - in addition to the anonymised first page of the paper. The editors would then have to delete the first page from the PDF before releasing it to the reviewing process (AFAIK the OJS system we use has no option to submit a separate title page which is only visible to the editor but not to the reviewers but then again I may be wrong).

**Comment by sieversMartin** [comment]
I have seen such a solution (with two different title pages) before. One could even split the PDF automatically within the LaTeX run using the "write18"-mode.
