### ISSUE TITLE
Compilation error due to new biblatex version

### ISSUE THREAD

**Issue by ghost** [sstrecker/emisa-latex-package#30]
I've downloaded the files from the repository, however ran into some problems while compiling the `emisa-author-template.tex` file. I declared the bibliography data base as `\bibliography{emisa.bib}` and also cited some publication from it using `parencite{key}` right at the beginning of the first introductory section.

Running `pdflatex`, `biber`, and again `pdflatex`

```
pdflatex emisa-author-template.tex
biber emisa-author-template
pdflatex emisa-author-template.tex
```

at the command line results in some errors:

```
! Undefined control sequence.
\abx@macro@name:family-giveninit ...#3#1}\ifempty
                                                  {#3}{}{\mkbibnameprefix {#...
l.66 \end
         {article}
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
?
```

which seems to be connected to a earlier commit made to handle some incompatibility introduced to some changes in the newest biblatex version. _Although the error message appears several times, the pdf output seems to be fine and as it should be._ Still throws me off, why the message is appearing in the first place, maybe worthwhile looking into.

I tested this on a fresh installation on MacTeX (2016) and also MikTeX (Windows), which both contained/downloaded the current version of biblatex. Both systems seem to be affected. I tried to resolve this issue, but mostly I don't know what the macros are for.

**Comment by sstrecker** [comment]
Dear David Becher:

We have started looking into that issue and will get back to you soon. However, due to vacation time in Germany, it may take us until mid-August to find a solution.

Best regards
Stefan Strecker

**Comment by sieversMartin** [comment]
I missed that error, because it is not shown directly. I am sorry for that. I'll fix it.

**Comment by sieversMartin** [comment]
`\ifempty` is indeed undefined. The bug results from problems with the `\ifblank` test, which I tried to resolve. I'll try to fix that soon.

**Comment by sieversMartin** [comment]
`\ifdefvoid` does the trick (cf. https://tex.stackexchange.com/questions/303930/problem-with-update-biblatex). A new version is available.

**Comment by sstrecker** [comment]
Dear David Becher:

Martin Sievers has provided a fix which is now available in GitHub as Version 2.1.1.

Best regards
S. Strecker 

## 

Prof. Dr. Stefan Strecker
Enterprise Modelling Research Group
Chair of Information Systems Development
University of Hagen
http://www.fernuni-hagen.de/evis
https://twitter.com/fuh_evis

Editor-in-Chief
'Enterprise Modelling and Information Systems Architectures
An International Journal'
https://emisa-journal.org
https://twitter.com/emisajournal

Chairman of the Dept./TC Business Informatics of the
German Informatics Society
http://fb-wi.gi.de 
https://www.gi.de

**Comment by sieversMartin** [comment]
Am 18.07.2016 um 16:36 schrieb Stefan Strecker:

> Dear David Becher:
> 
> Martin Sievers has provided a fix which is now available in GitHub as
> Version 2.1.1.

... and will be on CTAN within the next two days, i.e. TeX Live and
MiKTeX will update emisa within a week probably.

Best regards
Martin

## 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by ghost** [comment]
Dear Stefan Strecker,
Dear Martin Sievers,

Thanks for all the effort! I appreciate it!

Viele Grüße,
David Becher
