### ISSUE TITLE
British as standard option

### ISSUE THREAD

**Issue by sieversMartin** [sstrecker/emisa-latex-package#5]
Although "british" is considered to be the standard language, it always has to be explicitly stated as an option to \documentclass by an author.

It should become the standard, i.e. `\documentclass{emisa}` will be sufficient for a valid document.

**Comment by sstrecker** [comment]
Since the use of British English in academic writing has become rather unusual these days, I think  `\documentclass[british]{emisa}` serves as a reminder for the journal's language of choice. I agree, however, that both variants should be possible (i.e. `\documentclass{emisa}` should work as well).

**Comment by sstrecker** [comment]
After rethinking the issue, an alternative solution would be to have the class option 'review' (or 'referee') turn on a separate (initial) title page with full author information, abstract, keywords, acknowledgements and authornote - in addition to the anonymised first page of the paper. The editors would then have to delete the first page from the PDF before releasing it to the reviewing process (AFAIK the OJS system we use has no option to submit a separate title page which is only visible to the editor but not to the reviewers but then again I may be wrong).

**Comment by sieversMartin** [comment]
Solved with commit ed479e2cac66c0761bcce2220a9d37df933ab83c
