### ISSUE TITLE
Test and document commands for typesetting an appendix for an article 

### ISSUE THREAD

**Issue by sstrecker** [sstrecker/emisa-latex-package#9]
An earlier version of emisa.cls contains commands for typesetting an appendix to an article. These command must be tested with the current class and documented in the author instructions.

**Comment by sieversMartin** [comment]
The environment `articleappendix` can be used to add material to the end of the article. It can be stated right at the end of the `article` environment:

``` tex
\begin{article}{
   \title{}
   \subtitle{}
   \author*{<Name>}{<Email address>}
   \address{address line 1\\address line 2}
   \author{Name}
   \address[a]{}
   \abstract{}
   \keywords{Keyword 1 \and keyword 2\and keyword 3}
   \authornote{This article extends an earlier conference paper, see ...}
   \acknowledgements{}
   \bibliography{}
}
%% Please insert your article text here.

\begin{articleappendix*}
   \blindtext
\end{articleappendix*}
\printbibliography
\end{article}
```

`articleappendix` starts a new page while the starred version does not.

In Version 1.0 of the class file it was also used to set the affiliations given at the beginning of the article and thus a bit trickier. In the recent version nothing special is done, not even a heading is set.

**Comment by sstrecker** [comment]
Can this be documented in emisa.pdf?

**Comment by sieversMartin** [comment]
Yes, I'll do that.
